"use client";

import * as React from "react";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertTriangle, BarChart3, Building2, CheckCircle2, CreditCard, FileText, Headset, Loader2, Plus, Receipt, RefreshCw, ShieldCheck } from "lucide-react";

export default function InsuranceModulePage({ params }: { params: Promise<{ tenantId: string }> }) {
  const [tenantId,setTenantId]=React.useState("al-shifa");
  const [metrics,setMetrics]=React.useState<any>({});
  const [companies,setCompanies]=React.useState<any[]>([]); const [policies,setPolicies]=React.useState<any[]>([]); const [approvals,setApprovals]=React.useState<any[]>([]); const [claims,setClaims]=React.useState<any[]>([]);
  const [patients,setPatients]=React.useState<any[]>([]); const [branches,setBranches]=React.useState<any[]>([]);
  const [status,setStatus]=React.useState("all"); const [loading,setLoading]=React.useState(true); const [modal,setModal]=React.useState<"approval"|"claim"|null>(null);
  const [form,setForm]=React.useState({ patientId:"", policyId:"", branchId:"", requestedService:"MRI Lumbar Spine", requestedAmountCents:65000, approvedAmountCents:55000, serviceCode:"RAD-MRI-001", billedAmountCents:65000, status:"Submitted" });
  React.useEffect(()=>{params.then(p=>setTenantId(p.tenantId));},[params]);
  const fetchData=React.useCallback(async()=>{setLoading(true); const qs=new URLSearchParams({status}); const [dash,comp,pol,app,clm,pat,ov]=await Promise.all([fetch(`/api/imaging-insurance/${tenantId}/insurance-dashboard`).then(r=>r.json()),fetch(`/api/imaging-insurance/${tenantId}/insurance-companies`).then(r=>r.json()),fetch(`/api/imaging-insurance/${tenantId}/policies`).then(r=>r.json()),fetch(`/api/imaging-insurance/${tenantId}/approvals?${qs}`).then(r=>r.json()),fetch(`/api/imaging-insurance/${tenantId}/claims?${qs}`).then(r=>r.json()),fetch(`/api/clinic/${tenantId}/patients`).then(r=>r.json()),fetch(`/api/clinic/${tenantId}/overview`).then(r=>r.json())]); if(dash.success)setMetrics(dash.metrics); if(comp.success)setCompanies(comp.data||[]); if(pol.success)setPolicies(pol.data||[]); if(app.success)setApprovals(app.data||[]); if(clm.success)setClaims(clm.data||[]); if(pat.success)setPatients(pat.data||[]); if(ov.success)setBranches(ov.branches||[]); setForm(f=>({...f,patientId:pat.data?.[0]?.id||f.patientId,policyId:pol.data?.[0]?.id||f.policyId,branchId:ov.branches?.[0]?.id||f.branchId})); setLoading(false);},[tenantId,status]);
  React.useEffect(()=>{fetchData();},[fetchData]);
  async function createApproval(e:React.FormEvent){e.preventDefault(); const res=await fetch(`/api/imaging-insurance/${tenantId}/approvals`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const d=await res.json(); if(d.success){setModal(null); fetchData(); alert("Authorization approved and recorded.");} else alert(d.error);}
  async function createClaim(e:React.FormEvent){e.preventDefault(); const res=await fetch(`/api/imaging-insurance/${tenantId}/claims`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,diagnosisCodes:["M54.5","R52"]})}); const d=await res.json(); if(d.success){setModal(null); fetchData(); alert("Claim submitted with invoice and patient co-payment split.");} else alert(d.error);}
  async function resubmit(id:string){const res=await fetch(`/api/imaging-insurance/${tenantId}/claims/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"resubmit"})}); const d=await res.json(); if(d.success){fetchData(); alert("Rejected claim resubmitted successfully.");}}
  return <div className="p-6 space-y-6"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 bg-white dark:bg-slate-900 border rounded-2xl p-6"><div><h1 className="text-2xl font-black flex gap-2 items-center"><Headset className="text-teal-600"/> Insurance Module</h1><p className="text-xs text-slate-500">Companies, policies, coverage, approvals, claims, rejected claims, resubmission, invoices and billing rules.</p></div><div className="flex gap-2"><select value={status} onChange={e=>setStatus(e.target.value)} className="h-9 rounded-xl border px-3 text-xs font-bold dark:bg-slate-900"><option value="all">All Status</option><option>Pending</option><option>Authorized</option><option>Rejected</option><option>Submitted</option><option>Paid</option><option>Resubmitted</option></select><Button onClick={()=>setModal("approval")} variant="outline" className="font-black"><ShieldCheck className="w-4 h-4 mr-1"/>Approval</Button><Button onClick={()=>setModal("claim")} className="bg-teal-600 font-black"><Plus className="w-4 h-4 mr-1"/>Claim</Button></div></div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">{[{label:"Companies",v:metrics.companies,icon:Building2},{label:"Approvals",v:metrics.approvals,icon:ShieldCheck},{label:"Claims",v:metrics.claims,icon:Receipt},{label:"Rejected",v:metrics.rejected,icon:AlertTriangle}].map(k=>{const I=k.icon;return <Card key={k.label}><CardContent className="p-5 flex justify-between items-center"><div><p className="text-xs text-slate-500 font-black uppercase">{k.label}</p><p className="text-3xl font-black">{k.v||0}</p></div><I className="text-teal-600"/></CardContent></Card>})}</div>
    {loading?<div className="p-24 text-center"><Loader2 className="animate-spin text-teal-600 mx-auto"/></div>:<div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><Card><CardHeader><CardTitle>Insurance Companies</CardTitle></CardHeader><CardContent className="space-y-3">{companies.map(c=><div key={c.id} className="p-3 border rounded-xl text-xs"><p className="font-black">{c.name}</p><p className="font-mono text-slate-500">{c.payerCode}</p><Badge variant="success" className="mt-2">Billing Rules Active</Badge></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Policies & Coverage</CardTitle></CardHeader><CardContent className="space-y-3">{policies.map(p=><div key={p.id} className="p-3 border rounded-xl text-xs"><p className="font-black">{p.patientName}</p><p className="font-mono">{p.policyNumber} • {p.companyName}</p><div className="flex gap-1 mt-2"><Badge>{p.planName}</Badge><Badge variant="warning">Copay {p.coPaymentPercent}%</Badge></div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Insurance Reports</CardTitle><CardDescription>Revenue split and rejection analytics.</CardDescription></CardHeader><CardContent><div className="h-40 flex items-end gap-2">{claims.slice(0,6).map((c,i)=><div key={c.id} className="flex-1 bg-gradient-to-t from-teal-700 to-emerald-400 rounded-t" style={{height:`${Math.max(25,(c.billedAmountCents/70000)*100)}%`}} title={c.claimNumber}/>)}</div><p className="text-xs text-slate-500 mt-3">Claim volume by recent invoices.</p></CardContent></Card></div>}
    <Card><CardHeader><CardTitle>Claims & Rejected Claims Queue</CardTitle></CardHeader><CardContent className="space-y-4">{claims.map(c=><div key={c.id} className="p-4 border rounded-2xl"><div className="flex justify-between"><div><p className="font-black">{c.patientName}</p><p className="text-xs font-mono text-slate-500">{c.claimNumber} • {c.invoiceNumber} • {c.companyName}</p></div><Badge variant={c.status==="Rejected"?"destructive":c.status==="Paid"?"success":"warning"}>{c.status}</Badge></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div className="p-2 bg-slate-50 dark:bg-slate-800 rounded"><b>Billed</b><p>${(c.billedAmountCents/100).toFixed(0)}</p></div><div className="p-2 bg-slate-50 dark:bg-slate-800 rounded"><b>Insurance</b><p>${(c.insurancePayableCents/100).toFixed(0)}</p></div><div className="p-2 bg-slate-50 dark:bg-slate-800 rounded"><b>Co-Pay</b><p>${(c.patientCopaymentCents/100).toFixed(0)}</p></div></div>{c.status==="Rejected"&&<div className="mt-3 flex justify-between items-center p-3 bg-rose-50 text-rose-700 rounded-xl text-xs font-bold"><span>{c.rejectionReason||"Missing authorization."}</span><Button size="sm" onClick={()=>resubmit(c.id)}><RefreshCw className="w-4 h-4 mr-1"/>Resubmit</Button></div>}</div>)}</CardContent></Card>
    <Dialog open={!!modal} onOpenChange={()=>setModal(null)}><DialogContent><DialogHeader><DialogTitle>{modal==="approval"?"Create Authorization Request":"Submit Insurance Claim"}</DialogTitle><DialogDescription>Authorization, billing rules and patient co-payment are calculated dynamically.</DialogDescription></DialogHeader><form onSubmit={modal==="approval"?createApproval:createClaim} className="space-y-4"><div className="grid grid-cols-2 gap-3"><select className="h-9 rounded border text-xs" value={form.patientId} onChange={e=>setForm({...form,patientId:e.target.value})}>{patients.map(p=><option key={p.id} value={p.id}>{p.fullName}</option>)}</select><select className="h-9 rounded border text-xs" value={form.policyId} onChange={e=>setForm({...form,policyId:e.target.value})}>{policies.map(p=><option key={p.id} value={p.id}>{p.companyName} - {p.policyNumber}</option>)}</select></div>{modal==="claim"&&<select className="h-9 rounded border text-xs w-full" value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>}<Input value={modal==="approval"?form.requestedService:form.serviceCode} onChange={e=>modal==="approval"?setForm({...form,requestedService:e.target.value}):setForm({...form,serviceCode:e.target.value})}/><Input type="number" value={modal==="approval"?form.requestedAmountCents:form.billedAmountCents} onChange={e=>modal==="approval"?setForm({...form,requestedAmountCents:Number(e.target.value)}):setForm({...form,billedAmountCents:Number(e.target.value)})}/><DialogFooter><Button type="button" variant="outline" onClick={()=>setModal(null)}>Cancel</Button><Button type="submit" className="bg-teal-600">Submit</Button></DialogFooter></form></DialogContent></Dialog>
  </div>;
}