"use client";

import * as React from "react";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Activity, Camera, Download, Eye, FileImage, GitCompare, ImageUp, Loader2, Monitor, Plus, ScanLine, Search, ShieldCheck } from "lucide-react";

export default function RadiologyModulePage({ params }: { params: Promise<{ tenantId: string }> }) {
  const [tenantId, setTenantId] = React.useState("al-shifa");
  const [orders, setOrders] = React.useState<any[]>([]);
  const [patients, setPatients] = React.useState<any[]>([]);
  const [staff, setStaff] = React.useState<any[]>([]);
  const [branches, setBranches] = React.useState<any[]>([]);
  const [loading, setLoading] = React.useState(true);
  const [status, setStatus] = React.useState("all");
  const [modality, setModality] = React.useState("all");
  const [search, setSearch] = React.useState("");
  const [modalOpen, setModalOpen] = React.useState(false);
  const [viewer, setViewer] = React.useState<any | null>(null);
  const [form, setForm] = React.useState({ patientId:"", doctorId:"", branchId:"", modality:"MRI", bodyPart:"Lumbar Spine", priority:"Routine", clinicalIndication:"Low back pain with radiculopathy." });
  React.useEffect(()=>{params.then(p=>setTenantId(p.tenantId));},[params]);
  const fetchData = React.useCallback(async()=>{setLoading(true); const qs=new URLSearchParams({status,modality,search}); const [ord,pat,st,ov]=await Promise.all([fetch(`/api/imaging-insurance/${tenantId}/radiology?${qs}`).then(r=>r.json()),fetch(`/api/clinic/${tenantId}/patients`).then(r=>r.json()),fetch(`/api/clinic/${tenantId}/staff?staffType=Doctor`).then(r=>r.json()),fetch(`/api/clinic/${tenantId}/overview`).then(r=>r.json())]); if(ord.success)setOrders(ord.data||[]); if(pat.success)setPatients(pat.data||[]); if(st.success)setStaff(st.data||[]); if(ov.success)setBranches(ov.branches||[]); setForm(f=>({...f,patientId:pat.data?.[0]?.id||f.patientId,doctorId:st.data?.[0]?.id||f.doctorId,branchId:ov.branches?.[0]?.id||f.branchId})); setLoading(false);},[tenantId,status,modality,search]);
  React.useEffect(()=>{fetchData();},[fetchData]);
  async function createOrder(e:React.FormEvent){e.preventDefault(); const res=await fetch(`/api/imaging-insurance/${tenantId}/radiology`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const d=await res.json(); if(d.success){setModalOpen(false); fetchData(); alert("Radiology order created and modality worklist updated.");} else alert(d.error);}
  async function update(id:string, st:string){const payload:any={status:st}; if(st==="Reported"){payload.radiologistReport="DICOM images reviewed. No acute fracture. Mild degenerative changes."; payload.impression="Mild degenerative lumbar spondylosis.";} if(st==="DoctorReviewed") payload.doctorReviewNotes="Reviewed with patient and correlated clinically."; const res=await fetch(`/api/imaging-insurance/${tenantId}/radiology/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); const d=await res.json(); if(d.success){fetchData(); alert(`Radiology moved to ${st}`);} }
  return <div className="p-6 space-y-6"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 bg-white dark:bg-slate-900 border rounded-2xl p-6"><div><h1 className="text-2xl font-black flex gap-2 items-center"><ScanLine className="text-teal-600"/> Radiology Imaging Module</h1><p className="text-xs text-slate-500">X-Ray, MRI, CT, Ultrasound, DICOM upload, viewer, comparison, reports and history.</p></div><div className="flex flex-wrap gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search imaging orders..." className="h-9 rounded-xl border px-3 text-xs font-bold dark:bg-slate-900"/><select value={modality} onChange={e=>setModality(e.target.value)} className="h-9 rounded-xl border px-3 text-xs font-bold dark:bg-slate-900"><option value="all">All Modalities</option><option>X-Ray</option><option>MRI</option><option>CT</option><option>Ultrasound</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className="h-9 rounded-xl border px-3 text-xs font-bold dark:bg-slate-900"><option value="all">All Status</option><option>Ordered</option><option>ImageUploaded</option><option>Reported</option><option>DoctorReviewed</option></select><Button onClick={()=>setModalOpen(true)} className="bg-teal-600 font-black"><Plus className="w-4 h-4 mr-1"/>New Order</Button></div></div>
    {loading?<div className="p-24 text-center"><Loader2 className="animate-spin text-teal-600 mx-auto"/></div>:<div className="grid grid-cols-1 lg:grid-cols-2 gap-6">{orders.map(o=><Card key={o.id} className="hover:border-teal-500 transition-all"><CardHeader><div className="flex justify-between"><Badge variant={o.modality==="MRI"?"default":o.modality==="CT"?"warning":"secondary"}>{o.modality}</Badge><Badge variant={o.status==="DoctorReviewed"?"success":o.status==="Reported"?"warning":"outline"}>{o.status}</Badge></div><CardTitle className="mt-3 font-black">{o.patientName}</CardTitle><CardDescription className="font-mono text-xs">{o.orderNumber} • {o.mrn} • {o.bodyPart}</CardDescription></CardHeader><CardContent className="space-y-3 text-xs"><p><b>Indication:</b> {o.clinicalIndication}</p><p><b>Report:</b> {o.radiologistReport||"Pending radiologist interpretation."}</p><p><b>Impression:</b> {o.impression||"Pending"}</p><div className="flex gap-2 flex-wrap"><Badge><FileImage className="w-3 h-3 mr-1"/>{o.images?.length||0} DICOM</Badge><Badge variant="outline"><GitCompare className="w-3 h-3 mr-1"/>Comparison</Badge><Badge variant="success"><Monitor className="w-3 h-3 mr-1"/>Viewer Ready</Badge></div></CardContent><CardFooter className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>update(o.id,"ImageUploaded")}><ImageUp className="w-4 h-4 mr-1"/>Upload DICOM</Button><Button size="sm" variant="outline" onClick={()=>update(o.id,"Reported")}><Camera className="w-4 h-4 mr-1"/>Report</Button><Button size="sm" className="bg-teal-600" onClick={()=>update(o.id,"DoctorReviewed")}><ShieldCheck className="w-4 h-4 mr-1"/>Review</Button><Button size="sm" variant="outline" onClick={()=>setViewer(o)}><Eye className="w-4 h-4 mr-1"/>Viewer</Button><Button size="sm" variant="outline"><Download className="w-4 h-4 mr-1"/>PDF</Button></CardFooter></Card>)}</div>}
    <Dialog open={modalOpen} onOpenChange={setModalOpen}><DialogContent><DialogHeader><DialogTitle>Create Radiology Order</DialogTitle><DialogDescription>Send request to modality worklist.</DialogDescription></DialogHeader><form onSubmit={createOrder} className="space-y-4"><div className="grid grid-cols-3 gap-3"><select className="h-9 rounded border text-xs" value={form.patientId} onChange={e=>setForm({...form,patientId:e.target.value})}>{patients.map(p=><option key={p.id} value={p.id}>{p.fullName}</option>)}</select><select className="h-9 rounded border text-xs" value={form.doctorId} onChange={e=>setForm({...form,doctorId:e.target.value})}>{staff.map(s=><option key={s.id} value={s.id}>{s.user?.fullName}</option>)}</select><select className="h-9 rounded border text-xs" value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div><div className="grid grid-cols-3 gap-3"><select className="h-9 rounded border text-xs" value={form.modality} onChange={e=>setForm({...form,modality:e.target.value})}><option>X-Ray</option><option>MRI</option><option>CT</option><option>Ultrasound</option></select><Input value={form.bodyPart} onChange={e=>setForm({...form,bodyPart:e.target.value})}/><select className="h-9 rounded border text-xs" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>Routine</option><option>Urgent</option><option>STAT</option></select></div><div><Label className="text-xs font-bold">Clinical Indication</Label><textarea className="w-full rounded-xl border p-3 text-xs dark:bg-slate-900" rows={3} value={form.clinicalIndication} onChange={e=>setForm({...form,clinicalIndication:e.target.value})}/></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setModalOpen(false)}>Cancel</Button><Button type="submit" className="bg-teal-600">Create Order</Button></DialogFooter></form></DialogContent></Dialog>
    <Dialog open={!!viewer} onOpenChange={()=>setViewer(null)}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>DICOM Viewer & Comparison</DialogTitle></DialogHeader>{viewer&&<div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div className="h-80 rounded-2xl bg-slate-950 grid place-items-center text-teal-300"><div className="text-center"><ScanLine className="w-24 h-24 mx-auto"/><p className="font-mono mt-2">{viewer.dicomStudyUid}</p><p className="text-xs">{viewer.modality} {viewer.bodyPart}</p></div></div><pre className="bg-slate-950 text-emerald-400 rounded-2xl p-4 text-xs overflow-auto">{JSON.stringify({ history:viewer.historySnapshot, images:viewer.images, attachments:viewer.attachments, comparisonStudyOrderId:viewer.comparisonStudyOrderId },null,2)}</pre></div>}</DialogContent></Dialog>
  </div>;
}